core_controllers:
    resource: ../src/Core/Controller/
    type: attribute

dashboard_controller:
    resource: ../src/Dashboard/Controller/
    type: attribute

exercise_controllers:
    resource: ../src/Session/Controller/
    type: attribute

program_controllers:
    resource: ../src/Program/Controller/
    type: attribute

training_controllers:
    resource: ../src/Training/Controller/
    type: attribute
